from time import sleep
print("Ultimate AI Program.py")
print("Whats your name?")
name = input(">")
print("Where are you from?")
place = input(">")
print("What is your hobby?")
hobby = input(">")
print("Wait...")
sleep(1)
print("━━━━━━━", "10%")
sleep(1)
print("━━━━━━━━━━━━━━", "25%")
sleep(1)
print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━", "40%")
sleep(1)
print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━", "75%")
sleep(1)
print("━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━", "100%")
sleep(1)
print("Hi", name, "from", place, "who enjoys", hobby) 